### ISSUE TITLE
Builtin echo: Enabling environment variable expansion

### ISSUE THREAD

**Issue by tjlsimoes** [tjlsimoes/minishell#42]
The echo command ought to be able to called with environment variables.

Example: echo $USER ought to output to the terminal the value of $USER.

However, as of right now, the way we're parsing does not enable us to understand - on an Abstract Syntax Tree node level - what type of quotes were used: single or double. That is relevant as with single we ought not to expand.

Example: echo "$USER" creates the following AST
```
Type: NODE_COMMAND, Value: echo, FD: -1
Left:
  Type: NODE_ARGUMENT, Value: $USER, FD: -1
```

From within the node I have no way to know whether the value $USER was called with double quotes (") or single quotes (').

- Is this correct?
- How might we got about tackling this issue?
  - Perhaps adding another element to the node struct: to store the type of quote? Similarly to what we do on a token level?

**Comment by sfrnw** [comment]
i added information to the:

typedef struct s_ast_node
{
	t_node_type			type;
	char				*value;
	int					fd;
	char                quote_char;
	struct s_ast_node	*left;
	struct s_ast_node	*right;
}	t_ast_node;

examples: 

c2r2s10% ./minishell 
minishell> echo "$USER"
Type: NODE_COMMAND, Value: echo, FD: -1
, Quote: N
Left:
  Type: NODE_ARGUMENT, Value: $USER, FD: -1
, Quote: "
minishell> ^C
minishell> echo $USER'
minishell: sytax error: unclosed quote
minishell> echo '$USER'
Type: NODE_COMMAND, Value: echo, FD: -1
, Quote: N
Left:
  Type: NODE_ARGUMENT, Value: $USER, FD: -1
, Quote: '

**Comment by tjlsimoes** [comment]
Thanks! The execution still needs to take the added information into account.

For now there's still no environment variable expansion:

```
minishell> echo "$HOME"
Type: NODE_COMMAND, Value: echo, FD: -1, Quote: N
Left:
  Type: NODE_ARGUMENT, Value: $HOME, FD: -1, Quote: "
$HOME
```

I would have to take a look into this with care, but I would say that solving this will go through refactoring the current ft_echo() or ft_echo_exec() to make use of expand_env_var(). Expanding environment variables before generating the output.

**Comment by tjlsimoes** [comment]
The above identified issue seems to be now fixed:

```
minishell> echo "$HOME" '$HOME' $HOME "HI from $HOME" 'Hi from $HOME' '' $NON_EXISTANT "$NON_EXISTANT"
 '$NON_EXISTANT'
Type: NODE_COMMAND, Value: echo, FD: -1, Quote: N
Left:
  Type: NODE_ARGUMENT, Value: $HOME, FD: -1, Quote: "
  Right:
    Type: NODE_ARGUMENT, Value: $HOME, FD: -1, Quote: '
    Right:
      Type: NODE_ARGUMENT, Value: /home/pgr, FD: -1, Quote: N
      Right:
        Type: NODE_ARGUMENT, Value: HI from $HOME, FD: -1, Quote: "
        Right:
          Type: NODE_ARGUMENT, Value: Hi from $HOME, FD: -1, Quote: '
          Right:
            Type: NODE_ARGUMENT, Value: , FD: -1, Quote: '
            Right:
              Type: NODE_ARGUMENT, Value: , FD: -1, Quote: N
              Right:
                Type: NODE_ARGUMENT, Value: $NON_EXISTANT, FD: -1, Quote: "
                Right:
                  Type: NODE_ARGUMENT, Value: $NON_EXISTANT, FD: -1, Quote: '
/home/pgr $HOME /home/pgr HI from /home/pgr Hi from $HOME    $NON_EXISTANT
```
