### ISSUE TITLE
Redirections: parser review

### ISSUE THREAD

**Issue by tjlsimoes** [tjlsimoes/minishell#43]
Just some cases that may need to be reviewed to ensure proper handling:

##### Case 1
```echo "Hello" >output.txt``` is a valid Bash command, but
```
minishell> echo "Hello" >output.txt
minishell: syntax error near unexpected token: newline
Type: NODE_COMMAND, Value: echo, FD: -1, Quote: N
Left:
  Type: NODE_ARGUMENT, Value: Hello, FD: -1, Quote: "
Hello
```
##### Case 2
```echo "Hello">output.txt``` is a valid Bash command.

However our parsing is not identifying the redirection.

- We could possibly safeguard against this possibility by checking node arguments for redirections. But this may also not be the best approach.  
```
minishell> echo "Hello">output.txt
Type: NODE_COMMAND, Value: echo, FD: -1, Quote: N
Left:
  Type: NODE_ARGUMENT, Value: "Hello">output.txt, FD: -1, Quote: N
"Hello">output.txt
```

##### Case 3
```>output.txt echo "Hello"``` is a valid Bash command

More significantly here our parser is mistaking a node command argument with the command name.
More than **Case 2** this may prompt us to review our parser to accommodate the possibility of redirections appearing like so: redirection sign immediately followed by file, with no space in between. If that really is the problem here!

```
minishell> >output.txt echo "Hello"
Type: NODE_COMMAND, Value: Hello, FD: -1, Quote: N
Right:
  Type: NODE_REDIRECT_OUT, Value: echo, FD: 1, Quote: N
Hello: command not found
```

**Comment by tjlsimoes** [comment]
It seems that our parser isn't handling multiple redirections correctly when file names come immediately after the redirection signs:

```
minishell> ls >./outfile01 >>./outfile01 >./outfile02
Type: NODE_COMMAND, Value: ls, FD: -1, Quote: N
Right:
  Type: NODE_REDIRECT_OUT, Value: ./outfile01, FD: 1, Quote: N
  Right:
    Type: NODE_REDIRECT_APPEND, Value: >./outfile02, FD: 1, Quote: N
```

If the file names are not immediately after the redirection signs, everything seems to be as it should:

```
minishell> ls >./outfile01 >>./outfile01 >./outfile02
Type: NODE_COMMAND, Value: ls, FD: -1, Quote: N
Right:
  Type: NODE_REDIRECT_OUT, Value: ./outfile01, FD: 1, Quote: N
  Right:
    Type: NODE_REDIRECT_APPEND, Value: >./outfile02, FD: 1, Quote: N
```
