### ISSUE TITLE
Redirections: Instantiated with command order

### ISSUE THREAD

**Issue by tjlsimoes** [tjlsimoes/minishell#52]
Right now our code is failing on

```Test 120: ❌ ls >>./test_files/invalid_permission >>./outfiles/outfile02 <missing```

Adapting the command to isolate it from parsing problems, this is Minishell's output:

```
minishell> ls >> ./invalid_permission >> ./outfile02 < missing
Type: NODE_COMMAND, Value: ls, FD: -1, Quote: N
Right:
  Type: NODE_REDIRECT_APPEND, Value: ./invalid_permission, FD: 1, Quote: N
  Right:
    Type: NODE_REDIRECT_APPEND, Value: ./outfile02, FD: 1, Quote: N
    Right:
      Type: NODE_REDIRECT_IN, Value: missing, FD: 0, Quote: N
minishell: open error: missing
```

This is incorrect. Before any attempt at using `missing` as STDIN an error should occur from trying to append to a file to which the user has no permission.

Has is showcased here:

```
tjlsimoes@DESKTOP:~/repos/42/minishell$  ls >> ./invalid_permission >> ./outfile02 < missing
-bash: ./invalid_permission: Permission denied
```

This implies a refactoring of the order of redirection attempts.

Going from this logic:

```
	if (!gen_heredoc(ast))
		return (builtins_close_fds(orig_stdin, orig_stdout, fd_to_close));
	if (!gen_redirect_stdout(ast))
		return (builtins_close_fds(orig_stdin, orig_stdout, fd_to_close));
	if (!gen_redirect_in(ast))
		return (builtins_close_fds(orig_stdin, orig_stdout, fd_to_close));
```

To something that iterates the AST nodes and attempts redirections as they appear!

An alternative to this could be to add a scan - previous to any execution - that would simply check for valid descriptors and output errors accordingly.
